name: Load Testing Workflow

# Schedule the workflow to run on the !st day of the 3rd month at midnight

on:
  schedule:
  - cron: '0 0 1 */3 *'
  push:

jobs: 
  load_test:
    runs-on: ubuntu-latest
    steps:
    # Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v2

    # Install Dependecies
    - name: Install Dependecies
      uses: pip install -r requirements.txt

    # Run the load test using locust with specified parameters
    - name: Run Load Test
      run: locust -f load_test.py --headless --user=50 --spawn-rate=10 --host https://jsonplaceholder.typicode.com --run-time=4s