name: Matrix Strategy Example

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    steps:
    - name: Display matrix values
      run: |
        echo "Fruit: ${{ matrix.fruit }}"
        echo "Animal: ${{ matrix.animal }}"
        echo "Color: ${{ matrix.color }}"
        echo "Shape: ${{ matrix.shape }}"
